name: Deploy Backend to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Build OLD image name
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/dme-backend:latest .

      # Push OLD image name
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/dme-backend:latest

      # Deploy OLD image on EC2
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/dme-backend:latest

             docker stop dme-backend || true
             docker rm dme-backend || true

            docker run -d --restart unless-stopped \
              -p 5000:5000 \
              --name dme-backend \
              ${{ secrets.DOCKER_USERNAME }}/dme-backend:latest
